# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # set up JDK
    - name: Set Up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: esrally installation 
      run: |
        echo "install python3 and pip3"
        sudo apt-get install python3-pip python3-dev python3-setuptools
        echo "install esrally"
        sudo pip3 install esrally
      
        echo "run esrally default configuration"
        esrally configure
        
        echo "run basic test"
        esrally --distribution-version=6.5.3
